#! /bin/bash
########################################################################
# Author: Abhilash Raj
# Purpose: battery-notify reminds you to plug you laptop to power\
#  when battery is critically low and hibernates your system if \
# it battery is critically low.
##########################################################################


ACPI_OUTPUT=$(acpi -b)
NOTIFICATION_TITLE="Plug to power"
NOTIFICATION_BODY="You battery is critically low.\n Will soon hibernate."
BATTERY=`python battery.py $ACPI_OUTPUT`
BATTERY_LOW=12
BATTERY_CRITICALY_LOW=8

notify() {
   notify-send --expire-time="10000" \
   --urgency=critical "$NOTIFICATION_TITLE" "$NOTIFICATION_BODY";
}

while true ; do
   #main loop 
     sleep 10;
     #check if  the status of battery is too low
     if [ "$(acpi -a)" != 'Adapter 0 : on-line' ]; then 
	 if [ "$BATTERY" -lt "$BATTERY_LOW" ]; then  
	     notify;
	 fi
	 if [ "$BATTERY" -lt "$BATTERY_CRITICALY_LOW" ]; then
	     $(sudo hibernate); #a is the password for sudo
	 fi
     
     fi
done

exit 0