install:
	sudo apt-get install acpi
	sudo apt-get install libnotify-bin
	sudo apt-get install hibernate
	cp battery-notify  /usr/bin/
	cp battery.py /usr/bin
	chmod 755 /usr/bin/battery-notify

uninstall:
	rm /usr/bin/battery-notify
